# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pulseSequencerV4.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFormLayout,
    QGroupBox, QHBoxLayout, QLabel, QLineEdit,
    QMainWindow, QProgressBar, QPushButton, QSizePolicy,
    QStatusBar, QVBoxLayout, QWidget)

class Ui_odmr(object):
    def setupUi(self, odmr):
        if not odmr.objectName():
            odmr.setObjectName(u"odmr")
        odmr.resize(1242, 1000)
        odmr.setMinimumSize(QSize(0, 0))
        odmr.setMaximumSize(QSize(16777215, 16777215))
        self.centralwidget = QWidget(odmr)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(800, 600))
        self.horizontalLayout_2 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalWidget = QWidget(self.centralwidget)
        self.verticalWidget.setObjectName(u"verticalWidget")
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalWidget = QWidget(self.verticalWidget)
        self.horizontalWidget.setObjectName(u"horizontalWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy1)
        self.horizontalWidget.setMinimumSize(QSize(0, 100))
        self.horizontalLayout = QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.RedPitaya = QGroupBox(self.horizontalWidget)
        self.RedPitaya.setObjectName(u"RedPitaya")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.RedPitaya.sizePolicy().hasHeightForWidth())
        self.RedPitaya.setSizePolicy(sizePolicy2)
        self.RedPitaya.setMinimumSize(QSize(380, 100))
        font = QFont()
        font.setFamilies([u"Century Gothic"])
        font.setPointSize(12)
        self.RedPitaya.setFont(font)
        self.RedPitaya.setFlat(False)
        self.RedPitaya.setCheckable(False)
        self.lblPort = QLabel(self.RedPitaya)
        self.lblPort.setObjectName(u"lblPort")
        self.lblPort.setGeometry(QRect(20, 60, 111, 16))
        font1 = QFont()
        font1.setFamilies([u"Century Gothic"])
        self.lblPort.setFont(font1)
        self.btnConnect = QPushButton(self.RedPitaya)
        self.btnConnect.setObjectName(u"btnConnect")
        self.btnConnect.setGeometry(QRect(260, 30, 101, 51))
        self.txtPort = QLineEdit(self.RedPitaya)
        self.txtPort.setObjectName(u"txtPort")
        self.txtPort.setGeometry(QRect(130, 60, 113, 20))
        self.txtIP = QLineEdit(self.RedPitaya)
        self.txtIP.setObjectName(u"txtIP")
        self.txtIP.setGeometry(QRect(130, 30, 113, 20))
        self.lblIP = QLabel(self.RedPitaya)
        self.lblIP.setObjectName(u"lblIP")
        self.lblIP.setGeometry(QRect(20, 30, 91, 16))
        self.lblIP.setFont(font1)

        self.horizontalLayout.addWidget(self.RedPitaya, 0, Qt.AlignLeft)

        self.LaserControl = QGroupBox(self.horizontalWidget)
        self.LaserControl.setObjectName(u"LaserControl")
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.LaserControl.sizePolicy().hasHeightForWidth())
        self.LaserControl.setSizePolicy(sizePolicy3)
        self.LaserControl.setMinimumSize(QSize(320, 0))
        self.LaserControl.setFont(font)
        self.lblLowLevel = QLabel(self.LaserControl)
        self.lblLowLevel.setObjectName(u"lblLowLevel")
        self.lblLowLevel.setGeometry(QRect(30, 30, 101, 16))
        self.lblHighLevel = QLabel(self.LaserControl)
        self.lblHighLevel.setObjectName(u"lblHighLevel")
        self.lblHighLevel.setGeometry(QRect(30, 60, 101, 20))
        self.txtLowLevel = QLineEdit(self.LaserControl)
        self.txtLowLevel.setObjectName(u"txtLowLevel")
        self.txtLowLevel.setGeometry(QRect(140, 30, 61, 20))
        self.txtHighLevel = QLineEdit(self.LaserControl)
        self.txtHighLevel.setObjectName(u"txtHighLevel")
        self.txtHighLevel.setGeometry(QRect(140, 60, 61, 20))
        self.btnOpen = QPushButton(self.LaserControl)
        self.btnOpen.setObjectName(u"btnOpen")
        self.btnOpen.setGeometry(QRect(214, 30, 91, 51))

        self.horizontalLayout.addWidget(self.LaserControl, 0, Qt.AlignLeft)


        self.verticalLayout.addWidget(self.horizontalWidget)

        self.plotWidget = QWidget(self.verticalWidget)
        self.plotWidget.setObjectName(u"plotWidget")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy4)
        self.plotWidget.setMinimumSize(QSize(0, 0))
        self.plotLayout = QVBoxLayout(self.plotWidget)
        self.plotLayout.setObjectName(u"plotLayout")

        self.verticalLayout.addWidget(self.plotWidget)

        self.pbarProgress = QProgressBar(self.verticalWidget)
        self.pbarProgress.setObjectName(u"pbarProgress")
        sizePolicy5 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Maximum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.pbarProgress.sizePolicy().hasHeightForWidth())
        self.pbarProgress.setSizePolicy(sizePolicy5)
        self.pbarProgress.setValue(0)

        self.verticalLayout.addWidget(self.pbarProgress)


        self.horizontalLayout_2.addWidget(self.verticalWidget)

        self.verticalWidget1 = QWidget(self.centralwidget)
        self.verticalWidget1.setObjectName(u"verticalWidget1")
        sizePolicy3.setHeightForWidth(self.verticalWidget1.sizePolicy().hasHeightForWidth())
        self.verticalWidget1.setSizePolicy(sizePolicy3)
        self.verticalLayout_2 = QVBoxLayout(self.verticalWidget1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.MW = QGroupBox(self.verticalWidget1)
        self.MW.setObjectName(u"MW")
        self.MW.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.MW.sizePolicy().hasHeightForWidth())
        self.MW.setSizePolicy(sizePolicy2)
        self.MW.setMinimumSize(QSize(450, 250))
        self.MW.setFont(font)
        self.btnApply = QPushButton(self.MW)
        self.btnApply.setObjectName(u"btnApply")
        self.btnApply.setGeometry(QRect(360, 190, 75, 51))
        self.layoutWidget = QWidget(self.MW)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(30, 70, 312, 171))
        self.formLayout = QFormLayout(self.layoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.lblStartFreq = QLabel(self.layoutWidget)
        self.lblStartFreq.setObjectName(u"lblStartFreq")

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.lblStartFreq)

        self.txtStartFreq = QLineEdit(self.layoutWidget)
        self.txtStartFreq.setObjectName(u"txtStartFreq")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.txtStartFreq)

        self.lblStopFreq = QLabel(self.layoutWidget)
        self.lblStopFreq.setObjectName(u"lblStopFreq")

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.lblStopFreq)

        self.txtStopFreq = QLineEdit(self.layoutWidget)
        self.txtStopFreq.setObjectName(u"txtStopFreq")

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.txtStopFreq)

        self.lblCenterFreq = QLabel(self.layoutWidget)
        self.lblCenterFreq.setObjectName(u"lblCenterFreq")

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.lblCenterFreq)

        self.txtCenterFreq = QLineEdit(self.layoutWidget)
        self.txtCenterFreq.setObjectName(u"txtCenterFreq")

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.txtCenterFreq)

        self.lblRFPower = QLabel(self.layoutWidget)
        self.lblRFPower.setObjectName(u"lblRFPower")

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.lblRFPower)

        self.txtRFPower = QLineEdit(self.layoutWidget)
        self.txtRFPower.setObjectName(u"txtRFPower")

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.txtRFPower)

        self.lblTrigMode = QLabel(self.layoutWidget)
        self.lblTrigMode.setObjectName(u"lblTrigMode")

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.lblTrigMode)

        self.comboBoxMode = QComboBox(self.layoutWidget)
        self.comboBoxMode.addItem("")
        self.comboBoxMode.addItem("")
        self.comboBoxMode.addItem("")
        self.comboBoxMode.setObjectName(u"comboBoxMode")
        self.comboBoxMode.setAutoFillBackground(False)
        self.comboBoxMode.setSizeAdjustPolicy(QComboBox.AdjustToContents)

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.comboBoxMode)

        self.comboBoxMeasureType = QComboBox(self.MW)
        self.comboBoxMeasureType.setObjectName(u"comboBoxMeasureType")
        self.comboBoxMeasureType.setGeometry(QRect(360, 40, 76, 26))
        self.comboBoxMeasureType.setAutoFillBackground(False)
        self.comboBoxMeasureType.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.lblMeasureType = QLabel(self.MW)
        self.lblMeasureType.setObjectName(u"lblMeasureType")
        self.lblMeasureType.setGeometry(QRect(180, 40, 169, 27))
        self.btnConnect_2 = QPushButton(self.MW)
        self.btnConnect_2.setObjectName(u"btnConnect_2")
        self.btnConnect_2.setGeometry(QRect(360, 70, 81, 51))
        self.btnOn_Off = QPushButton(self.MW)
        self.btnOn_Off.setObjectName(u"btnOn_Off")
        self.btnOn_Off.setGeometry(QRect(360, 130, 75, 51))
        self.comboBoxMWdevice = QComboBox(self.MW)
        self.comboBoxMWdevice.addItem("")
        self.comboBoxMWdevice.setObjectName(u"comboBoxMWdevice")
        self.comboBoxMWdevice.setGeometry(QRect(20, 30, 90, 26))
        self.comboBoxMWdevice.setAutoFillBackground(False)
        self.comboBoxMWdevice.setSizeAdjustPolicy(QComboBox.AdjustToContents)

        self.verticalLayout_2.addWidget(self.MW)

        self.Scan = QGroupBox(self.verticalWidget1)
        self.Scan.setObjectName(u"Scan")
        sizePolicy1.setHeightForWidth(self.Scan.sizePolicy().hasHeightForWidth())
        self.Scan.setSizePolicy(sizePolicy1)
        self.Scan.setMinimumSize(QSize(0, 130))
        self.Scan.setFont(font)
        self.label = QLabel(self.Scan)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 30, 141, 21))
        self.cmbScanParam = QComboBox(self.Scan)
        self.cmbScanParam.setObjectName(u"cmbScanParam")
        self.cmbScanParam.setGeometry(QRect(170, 30, 111, 22))
        self.lblRange = QLabel(self.Scan)
        self.lblRange.setObjectName(u"lblRange")
        self.lblRange.setGeometry(QRect(100, 60, 61, 21))
        self.txtRange = QLineEdit(self.Scan)
        self.txtRange.setObjectName(u"txtRange")
        self.txtRange.setGeometry(QRect(170, 60, 111, 20))
        self.btnScanRabi = QPushButton(self.Scan)
        self.btnScanRabi.setObjectName(u"btnScanRabi")
        self.btnScanRabi.setGeometry(QRect(320, 30, 101, 51))
        self.lblCurrentValue = QLabel(self.Scan)
        self.lblCurrentValue.setObjectName(u"lblCurrentValue")
        self.lblCurrentValue.setGeometry(QRect(30, 60, 61, 21))
        self.lblIterations = QLabel(self.Scan)
        self.lblIterations.setObjectName(u"lblIterations")
        self.lblIterations.setGeometry(QRect(80, 90, 81, 16))
        self.txtIterations = QLineEdit(self.Scan)
        self.txtIterations.setObjectName(u"txtIterations")
        self.txtIterations.setGeometry(QRect(170, 90, 113, 20))
        self.lblCurrentIterations = QLabel(self.Scan)
        self.lblCurrentIterations.setObjectName(u"lblCurrentIterations")
        self.lblCurrentIterations.setGeometry(QRect(30, 90, 47, 16))

        self.verticalLayout_2.addWidget(self.Scan)

        self.Rabi = QGroupBox(self.verticalWidget1)
        self.Rabi.setObjectName(u"Rabi")
        self.Rabi.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.Rabi.sizePolicy().hasHeightForWidth())
        self.Rabi.setSizePolicy(sizePolicy2)
        self.Rabi.setMinimumSize(QSize(450, 220))
        self.Rabi.setFont(font)
        self.lblAveragesNumber = QLabel(self.Rabi)
        self.lblAveragesNumber.setObjectName(u"lblAveragesNumber")
        self.lblAveragesNumber.setGeometry(QRect(30, 180, 151, 21))
        self.txtAveragesNumber = QLineEdit(self.Rabi)
        self.txtAveragesNumber.setObjectName(u"txtAveragesNumber")
        self.txtAveragesNumber.setGeometry(QRect(202, 180, 81, 20))
        self.btnMeasure = QPushButton(self.Rabi)
        self.btnMeasure.setObjectName(u"btnMeasure")
        self.btnMeasure.setGeometry(QRect(320, 150, 91, 51))
        self.lblStartTime = QLabel(self.Rabi)
        self.lblStartTime.setObjectName(u"lblStartTime")
        self.lblStartTime.setGeometry(QRect(170, 30, 111, 16))
        self.lblDuration = QLabel(self.Rabi)
        self.lblDuration.setObjectName(u"lblDuration")
        self.lblDuration.setGeometry(QRect(320, 30, 101, 16))
        self.lblPump = QLabel(self.Rabi)
        self.lblPump.setObjectName(u"lblPump")
        self.lblPump.setGeometry(QRect(30, 60, 111, 21))
        self.txtStartPump = QLineEdit(self.Rabi)
        self.txtStartPump.setObjectName(u"txtStartPump")
        self.txtStartPump.setGeometry(QRect(170, 60, 113, 20))
        self.txtWidthPump = QLineEdit(self.Rabi)
        self.txtWidthPump.setObjectName(u"txtWidthPump")
        self.txtWidthPump.setGeometry(QRect(310, 60, 113, 20))
        self.txtWidthMW = QLineEdit(self.Rabi)
        self.txtWidthMW.setObjectName(u"txtWidthMW")
        self.txtWidthMW.setGeometry(QRect(310, 90, 113, 20))
        self.lblMW = QLabel(self.Rabi)
        self.lblMW.setObjectName(u"lblMW")
        self.lblMW.setGeometry(QRect(30, 90, 111, 21))
        self.txtStartMW = QLineEdit(self.Rabi)
        self.txtStartMW.setObjectName(u"txtStartMW")
        self.txtStartMW.setGeometry(QRect(170, 90, 113, 20))
        self.txtWidthImage = QLineEdit(self.Rabi)
        self.txtWidthImage.setObjectName(u"txtWidthImage")
        self.txtWidthImage.setGeometry(QRect(310, 120, 113, 20))
        self.lblImaging = QLabel(self.Rabi)
        self.lblImaging.setObjectName(u"lblImaging")
        self.lblImaging.setGeometry(QRect(30, 120, 121, 21))
        self.txtStartImage = QLineEdit(self.Rabi)
        self.txtStartImage.setObjectName(u"txtStartImage")
        self.txtStartImage.setGeometry(QRect(170, 120, 113, 20))
        self.lblReadout = QLabel(self.Rabi)
        self.lblReadout.setObjectName(u"lblReadout")
        self.lblReadout.setGeometry(QRect(30, 150, 121, 21))
        self.txtStartReadout = QLineEdit(self.Rabi)
        self.txtStartReadout.setObjectName(u"txtStartReadout")
        self.txtStartReadout.setGeometry(QRect(170, 150, 113, 20))

        self.verticalLayout_2.addWidget(self.Rabi)

        self.ODMR = QGroupBox(self.verticalWidget1)
        self.ODMR.setObjectName(u"ODMR")
        sizePolicy2.setHeightForWidth(self.ODMR.sizePolicy().hasHeightForWidth())
        self.ODMR.setSizePolicy(sizePolicy2)
        self.ODMR.setMinimumSize(QSize(450, 150))
        self.ODMR.setFont(font)
        self.btnStart = QPushButton(self.ODMR)
        self.btnStart.setObjectName(u"btnStart")
        self.btnStart.setGeometry(QRect(350, 30, 81, 81))
        self.lblRepeatNum = QLabel(self.ODMR)
        self.lblRepeatNum.setObjectName(u"lblRepeatNum")
        self.lblRepeatNum.setGeometry(QRect(30, 120, 71, 16))
        self.txtCountNumber = QLineEdit(self.ODMR)
        self.txtCountNumber.setObjectName(u"txtCountNumber")
        self.txtCountNumber.setGeometry(QRect(220, 60, 113, 20))
        self.lblThreshold = QLabel(self.ODMR)
        self.lblThreshold.setObjectName(u"lblThreshold")
        self.lblThreshold.setGeometry(QRect(30, 90, 151, 21))
        self.txtCountDuration = QLineEdit(self.ODMR)
        self.txtCountDuration.setObjectName(u"txtCountDuration")
        self.txtCountDuration.setGeometry(QRect(220, 30, 113, 20))
        self.ckbRepeatAdd = QCheckBox(self.ODMR)
        self.ckbRepeatAdd.setObjectName(u"ckbRepeatAdd")
        self.ckbRepeatAdd.setGeometry(QRect(170, 120, 161, 17))
        self.lblCountDuration = QLabel(self.ODMR)
        self.lblCountDuration.setObjectName(u"lblCountDuration")
        self.lblCountDuration.setGeometry(QRect(30, 30, 181, 21))
        self.txtThreshold = QLineEdit(self.ODMR)
        self.txtThreshold.setObjectName(u"txtThreshold")
        self.txtThreshold.setGeometry(QRect(220, 90, 113, 20))
        self.ckbRepeat = QCheckBox(self.ODMR)
        self.ckbRepeat.setObjectName(u"ckbRepeat")
        self.ckbRepeat.setGeometry(QRect(350, 120, 91, 17))
        self.lblCountNumber = QLabel(self.ODMR)
        self.lblCountNumber.setObjectName(u"lblCountNumber")
        self.lblCountNumber.setGeometry(QRect(30, 60, 181, 21))

        self.verticalLayout_2.addWidget(self.ODMR)

        self.DataSave = QGroupBox(self.verticalWidget1)
        self.DataSave.setObjectName(u"DataSave")
        sizePolicy1.setHeightForWidth(self.DataSave.sizePolicy().hasHeightForWidth())
        self.DataSave.setSizePolicy(sizePolicy1)
        self.DataSave.setMinimumSize(QSize(0, 130))
        self.DataSave.setFont(font)
        self.lblPath = QLabel(self.DataSave)
        self.lblPath.setObjectName(u"lblPath")
        self.lblPath.setGeometry(QRect(30, 30, 51, 16))
        self.txtPath = QLineEdit(self.DataSave)
        self.txtPath.setObjectName(u"txtPath")
        self.txtPath.setGeometry(QRect(90, 30, 341, 20))
        self.lblNum = QLabel(self.DataSave)
        self.lblNum.setObjectName(u"lblNum")
        self.lblNum.setGeometry(QRect(30, 60, 51, 16))
        self.txtNum = QLineEdit(self.DataSave)
        self.txtNum.setObjectName(u"txtNum")
        self.txtNum.setGeometry(QRect(90, 60, 41, 20))
        self.lblParamValue = QLabel(self.DataSave)
        self.lblParamValue.setObjectName(u"lblParamValue")
        self.lblParamValue.setGeometry(QRect(150, 60, 101, 16))
        self.txtParamValue = QLineEdit(self.DataSave)
        self.txtParamValue.setObjectName(u"txtParamValue")
        self.txtParamValue.setGeometry(QRect(250, 60, 81, 20))
        self.lblComment = QLabel(self.DataSave)
        self.lblComment.setObjectName(u"lblComment")
        self.lblComment.setGeometry(QRect(30, 90, 91, 16))
        self.txtComment = QLineEdit(self.DataSave)
        self.txtComment.setObjectName(u"txtComment")
        self.txtComment.setGeometry(QRect(130, 90, 201, 20))
        self.btnSave = QPushButton(self.DataSave)
        self.btnSave.setObjectName(u"btnSave")
        self.btnSave.setGeometry(QRect(350, 60, 81, 51))

        self.verticalLayout_2.addWidget(self.DataSave)


        self.horizontalLayout_2.addWidget(self.verticalWidget1)

        odmr.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(odmr)
        self.statusBar.setObjectName(u"statusBar")
        odmr.setStatusBar(self.statusBar)

        self.retranslateUi(odmr)

        QMetaObject.connectSlotsByName(odmr)
    # setupUi

    def retranslateUi(self, odmr):
        odmr.setWindowTitle(QCoreApplication.translate("odmr", u"ODMR & Rabi", None))
        self.RedPitaya.setTitle(QCoreApplication.translate("odmr", u"Red Pitaya settings", None))
        self.lblPort.setText(QCoreApplication.translate("odmr", u"Port Number:", None))
        self.btnConnect.setText(QCoreApplication.translate("odmr", u"Connect", None))
        self.lblIP.setText(QCoreApplication.translate("odmr", u"IP Address:", None))
        self.LaserControl.setTitle(QCoreApplication.translate("odmr", u"Laser control", None))
        self.lblLowLevel.setText(QCoreApplication.translate("odmr", u"Low level, V:", None))
        self.lblHighLevel.setText(QCoreApplication.translate("odmr", u"High level, V:", None))
        self.btnOpen.setText(QCoreApplication.translate("odmr", u"Open", None))
        self.MW.setTitle(QCoreApplication.translate("odmr", u"MW generator properties", None))
        self.btnApply.setText(QCoreApplication.translate("odmr", u"Apply", None))
        self.lblStartFreq.setText(QCoreApplication.translate("odmr", u"Start Frequency, MHz:", None))
        self.lblStopFreq.setText(QCoreApplication.translate("odmr", u"Stop Frequency, MHz:", None))
        self.lblCenterFreq.setText(QCoreApplication.translate("odmr", u"Center Freq, MHz:", None))
        self.lblRFPower.setText(QCoreApplication.translate("odmr", u"RF Power, dBm:", None))
        self.lblTrigMode.setText(QCoreApplication.translate("odmr", u"Trigger Mode:", None))
        self.comboBoxMode.setItemText(0, QCoreApplication.translate("odmr", u"0-No trigger", None))
        self.comboBoxMode.setItemText(1, QCoreApplication.translate("odmr", u"1-Full sweep", None))
        self.comboBoxMode.setItemText(2, QCoreApplication.translate("odmr", u"2- Step sweep", None))

        self.lblMeasureType.setText(QCoreApplication.translate("odmr", u"Measurment Type:", None))
        self.btnConnect_2.setText(QCoreApplication.translate("odmr", u"Connect", None))
        self.btnOn_Off.setText(QCoreApplication.translate("odmr", u"RF is Off", None))
        self.comboBoxMWdevice.setItemText(0, QCoreApplication.translate("odmr", u"SynthHD", None))

        self.Scan.setTitle(QCoreApplication.translate("odmr", u"Scan Control", None))
        self.label.setText(QCoreApplication.translate("odmr", u"Scan parameter:", None))
        self.lblRange.setText(QCoreApplication.translate("odmr", u"Range:", None))
        self.txtRange.setPlaceholderText(QCoreApplication.translate("odmr", u"start,stop,step_size", None))
        self.btnScanRabi.setText(QCoreApplication.translate("odmr", u"Scan Rabi", None))
        self.lblCurrentValue.setText("")
        self.lblIterations.setText(QCoreApplication.translate("odmr", u"Iterations:", None))
        self.lblCurrentIterations.setText("")
        self.Rabi.setTitle(QCoreApplication.translate("odmr", u"Rabi oscillations measurements", None))
        self.lblAveragesNumber.setText(QCoreApplication.translate("odmr", u"Averages number:", None))
        self.btnMeasure.setText(QCoreApplication.translate("odmr", u"Measure", None))
        self.lblStartTime.setText(QCoreApplication.translate("odmr", u"Start time, us:", None))
        self.lblDuration.setText(QCoreApplication.translate("odmr", u"Duration, us:", None))
        self.lblPump.setText(QCoreApplication.translate("odmr", u"Pump pulse:", None))
        self.lblMW.setText(QCoreApplication.translate("odmr", u"MW pulse:", None))
        self.lblImaging.setText(QCoreApplication.translate("odmr", u"Imaging pulse:", None))
        self.lblReadout.setText(QCoreApplication.translate("odmr", u"Readout pulse:", None))
        self.ODMR.setTitle(QCoreApplication.translate("odmr", u"ODMR measurements", None))
        self.btnStart.setText(QCoreApplication.translate("odmr", u"Start", None))
        self.lblRepeatNum.setText("")
        self.lblThreshold.setText(QCoreApplication.translate("odmr", u"Threshold, V:", None))
        self.ckbRepeatAdd.setText(QCoreApplication.translate("odmr", u"Repeat and Add", None))
        self.lblCountDuration.setText(QCoreApplication.translate("odmr", u"Counting duration, us:", None))
        self.ckbRepeat.setText(QCoreApplication.translate("odmr", u"Repeat", None))
        self.lblCountNumber.setText(QCoreApplication.translate("odmr", u"Counting number:", None))
        self.DataSave.setTitle(QCoreApplication.translate("odmr", u"Data saving", None))
        self.lblPath.setText(QCoreApplication.translate("odmr", u"Path:", None))
        self.lblNum.setText(QCoreApplication.translate("odmr", u"Num:", None))
        self.lblParamValue.setText(QCoreApplication.translate("odmr", u"Param. val.:", None))
        self.lblComment.setText(QCoreApplication.translate("odmr", u"Comment:", None))
        self.btnSave.setText(QCoreApplication.translate("odmr", u"Save", None))
    # retranslateUi

